version: '3.8'

services:
  deno-fresh-test:
    image: denoland/deno:2.0.3
    container_name: deno-fresh-test
    build:
      context: .
      dockerfile: docker/deno/Dockerfile
      #      args:
      #        USER_ID: 501
      #        GROUP_ID: 204
    volumes:
      - .:/home/deno/deno-fresh-test
    ports:
      - "8001:8001"
    # restart: unless-stopped
    command: ["task", "serve"]

    #  volumes:
    #    deno:

